server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/
spring:
  application:
    name: zuul-gateway


zuul:
  routes:
    six:
      path: /six/**
      serviceId: six-consumer



