server:
  port: 7777

spring:
  application:
    name: three-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

three-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule