server:
  port: 6666

spring:
  application:
    name: five-provider


management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/
  instance:
    prefer-ip-address: true

