server:
  port: 7778

spring:
  application:
    name: six-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,hystrix.stream
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: true


